### ISSUE TITLE
Upload files raster form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#476] opened 2020-10-15 11:25 UTC
What do we need to change to the way we handle uploading files?
We can think about:
- Do we give it a better place (earlier) in the user flow?
- Do we allow monitoring from the progress of the asynchronous task easier?
- Do we not forget the asynchronous task when changing screen (or even closing webpage?)
- D0 we provide feedback on a map showing the just uploaded raster data ?

Design by Lirry: https://github.com/nens/lizard-management-client/issues/237 (in Raster source form)

**Comment by hoanphungt** [comment] 2020-11-26 12:52
@Derryrover 
Hi Tom,

I made a commit to address your comment: https://github.com/nens/lizard-management-client/pull/517#issuecomment-732325437. The files are now sent recursively to lizard instead of all at once. Here is the commit that did the change: https://github.com/nens/lizard-management-client/pull/517/commits/9dfdeb830c0d8e7c937871427055529938b10590.

In addition, I made a PR to draft the upload queue here: https://github.com/nens/lizard-management-client/pull/529.

Could you review both of them?

Kr, Hoan

**Comment by Derryrover** [comment] 2020-11-26 14:02
@hoanphungt 

Hi Hoan,

It did some functional check and will now start the code review.
Functionaly I find it hard to review because:
- the visual design is not finished
- I tend to disagree with the queue approach (but maybe the design will  convince me).

I do see that the recursive code looks good (already checked that code) and also works well.
What might not work well yet, and stuff we need to consider, maybe even need backend work:

- The file only appears in the queue after it has been send. It needs to be there right away imo.
- Retrieving the asynchronous task fails on dev, maybe a proxy problem. Not sure if you worked on it already.
- The snackbar "finished uploading data" right after creating the raster source is now not true anymore-> factually the app is still busy uploading the data
- It is in general unclear that the user has to wait for the queue to finish. The user might close the app. Nothing is drawing the user to the queue yet. Do we need to add a notification or something?
- do we in general need to store references to the async taks on the backend somehow or in localstorage?
- It is not clear that the items in the queue belong to the raster. Is there a need to make this clear? What if a user uploads multiple rasters and one fails? Does she still know to which raster it belongs?

My recommendation:
Let us wait for the design. I feel there are so many open points here.
I do appreciate you working hard on this one and I think what you did is well,
but now we run the risk of restarting whole from the beginning again.

I will now proceed with code review

kr Tom

**Comment by Derryrover** [comment] 2020-11-26 14:05
@hoanphungt 
Code looks good !

**Comment by hoanphungt** [comment] 2020-12-03 14:38
@Derryrover 
Hi Tom,

The design from Lirry is ready here: https://github.com/nens/lizard-management-client/issues/532#issuecomment-736584751 plus with the updated user flow: https://github.com/nens/lizard-management-client/issues/237#issuecomment-736574689.

Thanks for your previous review and comment on this issue. It is now ready for review again. Here is the link to the PR: https://github.com/nens/lizard-management-client/issues/529.

Addressing your previous concerns:

- The file only appears in the queue after it has been send. It needs to be there right away imo. => FIXED
- Retrieving the asynchronous task fails on dev, maybe a proxy problem. Not sure if you worked on it already. => I have no problem retrieving async tasks, let me know if you still have this problem
- The snackbar "finished uploading data" right after creating the raster source is now not true anymore-> factually the app is still busy uploading the data => Changed to "Success! Raster source updated."
- It is in general unclear that the user has to wait for the queue to finish. The user might close the app. Nothing is drawing the user to the queue yet. Do we need to add a notification or something? => A red icon in the upload queue and if there are still files waiting to upload or in process of uploading then a window alert will appear to remind users.
- do we in general need to store references to the async taks on the backend somehow or in localstorage? => for now, no
- It is not clear that the items in the queue belong to the raster. Is there a need to make this clear? What if a user uploads multiple rasters and one fails? Does she still know to which raster it belong? => not for now as agreed with Lirry

Kr, Hoan

**Comment by Derryrover** [comment] 2020-12-04 14:01
@hoanphungt 

Hi Hoan, 
Looks good!
One comment regarding that the queue may be overwwritten in case the user uploads a second time files.
Please have a look if that is the case.
Other then that you can merge.

kr Tom

**Comment by hoanphungt** [comment] 2020-12-04 19:52
@Derryrover 
Thanks for your comment! You are indeed correct. It is currently overwriting old files in the queue. I updated the code.

**Comment by GeOdin** [comment] 2021-01-27 22:44
Hey,

While testing the uploading of the rasters, I noticed 2 bugs:

#### 1.
When you create a new raster source without data, get redirected to a page for creating a new raster and then uses the (green) back arrow in the upperleft corner of the management screen, the app crashes.
I made a new ticket for this one that can be found here:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/608

#### 2.
A custom color map of null also makes the management screens crash.
This ticket can be found here:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/609

Kind regards,
Madeleine

**Comment by GeOdin** [comment] 2021-01-27 23:01
There are still some things that I have not tested yet for this ticket.
I will probably test them on Friday:

* What happens when you try to create a raster source/ raster layer with a name that already exists?
* Try to add a raster layer to a raster source without data/ raster source with data (and what happens if the new data has the same name and extension as the current data)?
* add a custom colour map for all 3 options (adding a raster layer to a raster source without data, adding a raster layer to a raster source with existing data, changing a current raster layer)

**Comment by GeOdin** [comment] 2021-01-29 09:13
@hoanphungt 

Hey Hoan :)

I was wondering something, if you have added data to a raster source (when creating the raster source), you see that there is data in it in the raster source table:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/sources
But when you click on the raster source, you do not see the name of the previously added data.
Is this how it should be?

Some screenshots as example (for raster source madeleine-20210128-8):

![20210128-management-client-staging-raster-source-with-data-1-data-previous-rasters-loaded.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/802a9cb0-99f7-4c4e-b9c0-95918ad98429)

![20210128-management-client-staging-raster-source-with-data-2-raster-madeleine-has-size.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/b83ba452-a776-4417-9809-62125acafe82)

![20210128-management-client-staging-raster-source-with-data-3-raster-madeleine-has-size-data-not-shown.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/e05c1d8b-ad2a-4300-9c82-36790ff6e001)

Kind regards,
Madeleine

**Comment by hoanphungt** [comment] 2021-01-29 09:43
@GeOdin
Hi Madeleine,

You are correct. The previous uploaded files for the raster will not be shown in the form. This is also how it worked in the old management client. I am not sure if we can show previous uploaded files for a raster.

@lexvand and @LirryPinter 
Hi Lex and Lirry,

The Raster source form does not show previous uploaded files. I see that the same situation is for the old management client. Do you guys know if there is a technical limitation here to show previous uploaded files and if the current workflow is as intended or we actually want to show previous uploaded files in the form as well?

Kr, Hoan

**Comment by lexvand** [comment] 2021-01-29 10:30
@hoanphungt No way to keep track of that on the longterm. So don't bother.

**Comment by GeOdin** [comment] 2021-02-02 08:41
While testing this ticket, I noticed that there are a lot of raster sources currently on staging with no name.
This results in a lot of blanc lines in the drop down of 2: DATA Source when creating a new raster layer.
I made a ticket for this to think about it:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/623

Kind regards,
Madeleine

**Comment by GeOdin** [comment] 2021-02-04 08:20
Hey guys :)

Some final comments  before closing this ticket:

* adding a raster with no data values gives a 404 task error (backend ticket):
https://app.zenhub.com/workspaces/team-lizard-5ef307a0fac67c0022166258/issues/nens/lizard-nxt/4823
* there currently is not yet an asterix for the required data field (frontend):
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/630


Kind regards,
Madeleine

**Closed** 2021-02-04 08:20 UTC
Labels: UX/UI, enhancement
