### ISSUE TITLE
Name fields have max length of 30

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#696] opened 2021-03-01 15:54 UTC
Ca we add field validation to first and last name in Contacts form. Max_length is 30 according to the API response.

**Comment by hoanphungt** [comment] 2021-03-02 07:51
Correct! something goes wrong with the regex expression used to validate email address. According to this: https://stackoverflow.com/questions/29551388/performance-issue-while-evaluating-email-address-with-a-regular-expression, the `?` in the expression caused the catastrophic backtracking issue. I removed the `?` in the expression and the issue is resolved.

**Comment by hoanphungt** [comment] 2021-03-02 07:52
Merged in PR: https://github.com/nens/lizard-management-client/pull/699

**Closed** 2021-03-10 16:45 UTC
Labels: Sprint disruption, enhancement
